web50/projects/2020/fall/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("random", views.random, name="random"),
    path("add", views.add, name="add"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("update", views.update, name="update"),
    path("search", views.search, name="search"),
    path("wiki/<str:entry>", views.content, name="content")
]

web50/projects/2020/fall/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    # path('wiki/', include("encyclopedia.urls"))
]

web50/projects/2020/fall/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

web50/projects/2020/fall/wiki/encyclopedia/views.py
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
import markdown2
import random as rmd


from . import util


class NewTaskForm(forms.Form):
    title = forms.CharField(label="Title")
    entry_description = forms.CharField(widget=forms.Textarea)


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def content(request, entry):
    content = util.get_entry(entry)
    if content == None:
        entry = None
    else:
        content = markdown2.markdown(content)

    return render(request, "encyclopedia/entry.html", {
        "entry": entry,
        "content": content
    })


def random(request):
    entries = util.list_entries()
    random_entry = rmd.choice(entries)
    return HttpResponseRedirect(reverse("wiki:content", args=[random_entry]))


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            existing_entries = util.list_entries()
            title = form.cleaned_data["title"]
            description = form.cleaned_data["entry_description"]
            # checks if an entry with that title already exists
            if (title in existing_entries):
                return HttpResponse("An entry with that title already exists")
            else:
                new_entry = util.save_entry(title, description)
                return HttpResponseRedirect(reverse("wiki:content", args=[title]))
    return render(request, "encyclopedia/add.html", {
        "form": NewTaskForm()
    })


def edit(request, entry):
    content = util.get_entry(entry)
    form = NewTaskForm()
    # pre-populates fields
    form["title"].initial = entry
    form["entry_description"].initial = content
    return render(request, "encyclopedia/edit.html", {
        "form": form
    })


def update(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["entry_description"]
            new_entry = util.save_entry(title, description)
            return HttpResponseRedirect(reverse("wiki:content", args=[title]))


def search(request):
    q = request.GET.get('q')
    existing_entries = util.list_entries()
    # checks if search has an exact match
    if (q in existing_entries):
        return HttpResponseRedirect(reverse("wiki:content", args=[q]))
    # otherwise looks for substrings of the search
    else:
        matches = [i for i in existing_entries if q in i]
        return render(request, "encyclopedia/search.html", {
            "matches": matches
        })

web50/projects/2020/fall/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create
{% endblock %}

{% block body %}
<h1>Create new entry</h1>

<form action="{% url 'wiki:add' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

{% endblock %}

web50/projects/2020/fall/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit
{% endblock %}

{% block body %}
<h1>Edit entry</h1>

<form action="{% url 'wiki:update' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <br><input class="btn btn-primary" type="submit">
</form>

{% endblock %}

web50/projects/2020/fall/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{% if content == None %}
error
{% else %}
{{ entry }}
{% endif %}
{% endblock %}

{% block body %}

{% if content == None %}
<h1>Page not found</h1>
{% else %}
{{ content|safe }}
{% endif %}
<a href="{% url 'wiki:edit' entry=entry %}">
    <button class="btn btn-primary" type="submit">Edit</button>
</a>

{% endblock %}

web50/projects/2020/fall/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li><a href="{% url 'wiki:content' entry=entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

web50/projects/2020/fall/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'wiki:search' %}">
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'wiki:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'wiki:add' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'wiki:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

web50/projects/2020/fall/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search
{% endblock %}

{% block body %}
<h1>Search Results</h1>

{% for entry in matches %}
<li><a href="{% url 'wiki:content' entry=entry %}">{{ entry }}</a></li>
{% empty %}
No results match your search
{% endfor %}

{% endblock %}